Repository Committee-of-System-Library/Notice_Sender, pull requests merged in 2023-03, with the labels that each got.

#13 fix: NoticeMessage의 findByNotice 중복 데이터 에러 해결, 로직 변경
  src/main/java/com/knu/noticesender/core/model/BaseEntity.java
  src/main/java/com/knu/noticesender/notice/dto/NoticeMessageDto.java
  src/main/java/com/knu/noticesender/notice/service/NoticeMessageService.java
  src/main/java/com/knu/noticesender/notice/service/NoticeRecordService.java
Labels: bug fix

#14 Logging 파일 저장, Logging Filter 추가
  src/main/java/com/knu/noticesender/core/dto/Result.java
  src/main/java/com/knu/noticesender/logger/LoggingFilter.java
  src/main/java/com/knu/noticesender/logger/RequestWrapper.java
  src/main/java/com/knu/noticesender/logger/ResponseWrapper.java
  src/main/java/com/knu/noticesender/notice/NoticeDiscordSender.java
  src/main/java/com/knu/noticesender/notice/NoticeSender.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: documentation

#16 feat: 공지 저장 전용 기능 추가(알림 x)
  src/main/java/com/knu/noticesender/notice/controller/NoticeController.java
  src/main/java/com/knu/noticesender/notice/service/NoticeProcessService.java
  src/main/java/com/knu/noticesender/notice/service/NoticeSaveService.java
  src/main/resources/application-local.yml
Labels: new feature

#17 feat: 서버 time-zone(Asia/Seoul) 설정 추가
  src/main/java/com/knu/noticesender/config/timeZoneConfig.java
Labels: new feature

#19 fix: 로그 time-zone 세팅
  src/main/resources/logback-spring.xml
Labels: bug fix

#21 Add: payload 로깅에서 제외할 uri 목록 추가 및 로깅 제외
  src/main/java/com/knu/noticesender/logger/LoggingFilter.java
  src/main/java/com/knu/noticesender/notice/service/NoticeSaveService.java
  src/main/resources/application-local.yml
Labels: documentation

#22 Feat: Response 규칙, Exception 규칙 클래스 추가
  src/main/java/com/knu/noticesender/core/controller/HelloController.java
  src/main/java/com/knu/noticesender/core/exception/CommonExceptionHandler.java
  src/main/java/com/knu/noticesender/core/exception/KnuException.java
  src/main/java/com/knu/noticesender/core/response/ApiResponse.java
  src/main/java/com/knu/noticesender/core/response/ResponseResult.java
  src/main/java/com/knu/noticesender/core/response/ResultCode.java
Labels: new feature
