Repository Committee-of-System-Library/Notice_Sender, pull requests merged in 2023-02, with the labels that each got.

#2 Notice Model 추가
  src/main/java/com/knu/noticesender/notice/dto/NoticeDto.java
  src/main/java/com/knu/noticesender/notice/model/Category.java
  src/main/java/com/knu/noticesender/notice/model/Notice.java
  src/main/java/com/knu/noticesender/notice/model/NoticeType.java
Labels: documentation

#3 Add: Discord Sender 추가
  src/main/java/com/knu/noticesender/config/CategoryUrlMapper.java
  src/main/java/com/knu/noticesender/config/DiscordConfig.java
  src/main/java/com/knu/noticesender/notice/NoticeDiscordSender.java
  src/main/java/com/knu/noticesender/notice/dto/NoticeDto.java
Labels: enhancement

#4 Enum Class Converter 추가
  src/main/java/com/knu/noticesender/notice/model/Category.java
  src/main/java/com/knu/noticesender/notice/model/Convertible.java
  src/main/java/com/knu/noticesender/notice/model/Notice.java
  src/main/java/com/knu/noticesender/notice/model/NoticeType.java
  src/main/java/com/knu/noticesender/notice/utils/CategoryConverter.java
  src/main/java/com/knu/noticesender/notice/utils/EnumDbConvertUtils.java
  src/main/java/com/knu/noticesender/notice/utils/NoticeTypeConverter.java
Labels: enhancement

#5 NoticeDto 내 Discord 관련 의존 제거, DiscordMessage(+Converter) Class 추가
  src/main/java/com/knu/noticesender/notice/NoticeDiscordSender.java
  src/main/java/com/knu/noticesender/notice/NoticeMailSender.java
  src/main/java/com/knu/noticesender/notice/api/NoticeMailSenderApi.java
  src/main/java/com/knu/noticesender/notice/dto/NoticeDto.java
  src/main/java/com/knu/noticesender/notice/dto/discord/DiscordMessage.java
  src/main/java/com/knu/noticesender/notice/repository/NoticeRepository.java
  src/main/java/com/knu/noticesender/notice/service/NoticeService.java
  src/main/java/com/knu/noticesender/notice/utils/NoticeDiscordMessageConverter.java
Labels: documentation

#7 gitignore 파일 추가
  .gitignore
Labels: enhancement

#6 NoticeRecord 추가에 따른 변경 사항
  src/main/java/com/knu/noticesender/config/SenderConfig.java
  src/main/java/com/knu/noticesender/notice/NoticeSender.java
  src/main/java/com/knu/noticesender/notice/api/NoticeMailSenderApi.java
  src/main/java/com/knu/noticesender/notice/dto/NoticeDto.java
  src/main/java/com/knu/noticesender/notice/model/Notice.java
  src/main/java/com/knu/noticesender/notice/model/NoticeRecord.java
  src/main/java/com/knu/noticesender/notice/model/Sender.java
  src/main/java/com/knu/noticesender/notice/repository/NoticeRecordRepository.java
  src/main/java/com/knu/noticesender/notice/repository/NoticeRepository.java
  src/main/java/com/knu/noticesender/notice/service/NoticeRecordService.java
  src/main/java/com/knu/noticesender/notice/service/NoticeService.java
Labels: enhancement

#8 메시지 양식 변경, NoticeSenderManager Class 추가, application.yml 파일 공개,
  src/main/java/com/knu/noticesender/notice/NoticeSenderManager.java
  src/main/java/com/knu/noticesender/notice/SenderManager.java
  src/main/java/com/knu/noticesender/notice/dto/discord/DiscordMessage.java
  src/main/java/com/knu/noticesender/notice/model/Notice.java
  src/main/java/com/knu/noticesender/notice/model/NoticeRecord.java
  src/main/java/com/knu/noticesender/notice/model/NoticeType.java
  src/main/java/com/knu/noticesender/notice/repository/NoticeRecordRepository.java
  src/main/java/com/knu/noticesender/notice/service/NoticeRecordService.java
  src/main/java/com/knu/noticesender/notice/utils/NoticeDiscordMessageConverter.java
  src/main/resources/application.yml
Labels: enhancement

#9 Notice, NoticeRecord 필드(Column) 추가, DB Context 확정에 따른 변경 사항
  src/main/java/com/knu/noticesender/config/CategoryUrlMapper.java
  src/main/java/com/knu/noticesender/config/DiscordConfig.java
  src/main/java/com/knu/noticesender/notice/NoticeDiscordSender.java
  src/main/java/com/knu/noticesender/notice/dto/NoticeDto.java
  src/main/java/com/knu/noticesender/notice/model/Category.java
  src/main/java/com/knu/noticesender/notice/model/Notice.java
  src/main/java/com/knu/noticesender/notice/model/NoticeRecord.java
  src/main/java/com/knu/noticesender/notice/model/NoticeType.java
  src/main/java/com/knu/noticesender/notice/service/NoticeRecordService.java
  src/main/java/com/knu/noticesender/notice/service/NoticeService.java
  src/main/resources/application.yml
Labels: documentation

#11 공지 저장/업데이트 서비스 추가 및 프로세스 서비스 추가, 메세지 기능 서비스 추가 및 엔티티 추가 생성
  build.gradle
  src/main/java/com/knu/noticesender/NoticeSenderApplication.java
  src/main/java/com/knu/noticesender/core/dto/Result.java
  src/main/java/com/knu/noticesender/core/model/BaseEntity.java
  src/main/java/com/knu/noticesender/notice/NoticeSenderManager.java
  src/main/java/com/knu/noticesender/notice/controller/NoticeController.java
  src/main/java/com/knu/noticesender/notice/dto/NoticeSaveReqDto.java
  src/main/java/com/knu/noticesender/notice/model/Notice.java
  src/main/java/com/knu/noticesender/notice/model/NoticeMessage.java
  src/main/java/com/knu/noticesender/notice/model/NoticeRecord.java
  src/main/java/com/knu/noticesender/notice/model/NoticeType.java
  src/main/java/com/knu/noticesender/notice/repository/NoticeMessageRepository.java
  src/main/java/com/knu/noticesender/notice/repository/NoticeRepository.java
  src/main/java/com/knu/noticesender/notice/service/NoticeMessageService.java
  src/main/java/com/knu/noticesender/notice/service/NoticeProcessService.java
  src/main/java/com/knu/noticesender/notice/service/NoticeRecordService.java
  src/main/java/com/knu/noticesender/notice/service/NoticeSaveService.java
  src/main/resources/application.yml
Labels: new feature
